a = int(input("Please enter the first number: "))
b = int(input("Please enter the first number: "))

# Add = (a+b)
print("Addition of", a, "and", b, "is:", (a+b))
# Subtract = (a-b)
print("Subtraction of", a, "and", b, "is:", (a-b))
# Divide = (a/b)
print("Division of", a, "and", b, "is:", (a/b))
# FloatDivide = (a//b)
print("Float Division of", a, "and", b, "is:", (a//b))
# Multiply = (a*b)
print("Multiplication of", a, "and", b, "is:", (a*b))
# Power = (a**b)
print("The result of", a, "raised to the power", b, "is:", (a**b))
# Modulus = (a%b)
print("Remainder when", a, "is", "divided by",b, "is:", (a%b))